/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using customer.Client;
using customer.Api;
// uncomment below to import models
//using customer.Model;

namespace customer.Test.Api
{
    /// <summary>
    ///  Class for testing CustomerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CustomerApiTests : IDisposable
    {
        private CustomerApi instance;

        public CustomerApiTests()
        {
            instance = new CustomerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CustomerApi
            //Assert.IsType<CustomerApi>(instance);
        }

        /// <summary>
        /// Test CustomerAcquireSubscriber
        /// </summary>
        [Fact]
        public void CustomerAcquireSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateSubscriberRequest body = null;
            //var response = instance.CustomerAcquireSubscriber(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerAcquireSubscriber2
        /// </summary>
        [Fact]
        public void CustomerAcquireSubscriber2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateSubscriberRequest body = null;
            //var response = instance.CustomerAcquireSubscriber2(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerAcquireUnsubscriber
        /// </summary>
        [Fact]
        public void CustomerAcquireUnsubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUnsubscribeRequest body = null;
            //var response = instance.CustomerAcquireUnsubscriber(body);
            //Assert.IsType<CustomerUnsubscribeResponse>(response);
        }

        /// <summary>
        /// Test CustomerAcquireUnsubscriber2
        /// </summary>
        [Fact]
        public void CustomerAcquireUnsubscriber2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUnsubscribeRequest body = null;
            //var response = instance.CustomerAcquireUnsubscriber2(body);
            //Assert.IsType<CustomerUnsubscribeResponse>(response);
        }

        /// <summary>
        /// Test CustomerAddCustomerToGroup
        /// </summary>
        [Fact]
        public void CustomerAddCustomerToGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddCustomerToGroupRequest body = null;
            //var response = instance.CustomerAddCustomerToGroup(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerAddCustomerToGroup2
        /// </summary>
        [Fact]
        public void CustomerAddCustomerToGroup2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddCustomerToGroupRequest body = null;
            //var response = instance.CustomerAddCustomerToGroup2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerAssignAgent
        /// </summary>
        [Fact]
        public void CustomerAssignAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAssignAgentRequest body = null;
            //var response = instance.CustomerAssignAgent(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerBulkUpdate
        /// </summary>
        [Fact]
        public void CustomerBulkUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerBulkUpdateRequest body = null;
            //var response = instance.CustomerBulkUpdate(body);
            //Assert.IsType<CustomerBulkUpdateResponse>(response);
        }

        /// <summary>
        /// Test CustomerBulkUpdate2
        /// </summary>
        [Fact]
        public void CustomerBulkUpdate2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerBulkUpdateRequest body = null;
            //var response = instance.CustomerBulkUpdate2(body);
            //Assert.IsType<CustomerBulkUpdateResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreate
        /// </summary>
        [Fact]
        public void CustomerCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateRequest body = null;
            //var response = instance.CustomerCreate(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreate2
        /// </summary>
        [Fact]
        public void CustomerCreate2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateRequest body = null;
            //var response = instance.CustomerCreate2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateAddress
        /// </summary>
        [Fact]
        public void CustomerCreateAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressCreateRequest body = null;
            //var response = instance.CustomerCreateAddress(body);
            //Assert.IsType<CustomerAddressCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateAddress2
        /// </summary>
        [Fact]
        public void CustomerCreateAddress2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressCreateRequest body = null;
            //var response = instance.CustomerCreateAddress2(body);
            //Assert.IsType<CustomerAddressCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateGroup
        /// </summary>
        [Fact]
        public void CustomerCreateGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateGroupRequest body = null;
            //var response = instance.CustomerCreateGroup(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateGroup2
        /// </summary>
        [Fact]
        public void CustomerCreateGroup2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateGroupRequest body = null;
            //var response = instance.CustomerCreateGroup2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateSubscriber
        /// </summary>
        [Fact]
        public void CustomerCreateSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateSubscriberRequest body = null;
            //var response = instance.CustomerCreateSubscriber(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerCreateSubscriber2
        /// </summary>
        [Fact]
        public void CustomerCreateSubscriber2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCreateSubscriberRequest body = null;
            //var response = instance.CustomerCreateSubscriber2(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerDeleteAddress
        /// </summary>
        [Fact]
        public void CustomerDeleteAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressDeleteRequest body = null;
            //var response = instance.CustomerDeleteAddress(body);
            //Assert.IsType<CustomerAddressDeleteResponse>(response);
        }

        /// <summary>
        /// Test CustomerDeleteAddress2
        /// </summary>
        [Fact]
        public void CustomerDeleteAddress2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressDeleteRequest body = null;
            //var response = instance.CustomerDeleteAddress2(body);
            //Assert.IsType<CustomerAddressDeleteResponse>(response);
        }

        /// <summary>
        /// Test CustomerDeleteGroup
        /// </summary>
        [Fact]
        public void CustomerDeleteGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerDeleteGroupRequest body = null;
            //var response = instance.CustomerDeleteGroup(body);
            //Assert.IsType<CustomerDeleteGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerDeleteGroup2
        /// </summary>
        [Fact]
        public void CustomerDeleteGroup2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerDeleteGroupRequest body = null;
            //var response = instance.CustomerDeleteGroup2(body);
            //Assert.IsType<CustomerDeleteGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerFind
        /// </summary>
        [Fact]
        public void CustomerFindTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindManyRequest body = null;
            //var response = instance.CustomerFind(body);
            //Assert.IsType<CustomerFindManyResponse>(response);
        }

        /// <summary>
        /// Test CustomerFind2
        /// </summary>
        [Fact]
        public void CustomerFind2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindManyRequest body = null;
            //var response = instance.CustomerFind2(body);
            //Assert.IsType<CustomerFindManyResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindByEmail
        /// </summary>
        [Fact]
        public void CustomerFindByEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindByEmailRequest body = null;
            //var response = instance.CustomerFindByEmail(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindByEmail2
        /// </summary>
        [Fact]
        public void CustomerFindByEmail2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindByEmailRequest body = null;
            //var response = instance.CustomerFindByEmail2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindById
        /// </summary>
        [Fact]
        public void CustomerFindByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindByIdRequest body = null;
            //var response = instance.CustomerFindById(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindById2
        /// </summary>
        [Fact]
        public void CustomerFindById2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindByIdRequest body = null;
            //var response = instance.CustomerFindById2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindSubscriberByEmail
        /// </summary>
        [Fact]
        public void CustomerFindSubscriberByEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindSubscriberByEmailRequest body = null;
            //var response = instance.CustomerFindSubscriberByEmail(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindSubscriberByEmail2
        /// </summary>
        [Fact]
        public void CustomerFindSubscriberByEmail2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindSubscriberByEmailRequest body = null;
            //var response = instance.CustomerFindSubscriberByEmail2(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindSubscriberById
        /// </summary>
        [Fact]
        public void CustomerFindSubscriberByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindSubscriberByIdRequest body = null;
            //var response = instance.CustomerFindSubscriberById(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerFindSubscriberById2
        /// </summary>
        [Fact]
        public void CustomerFindSubscriberById2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerFindSubscriberByIdRequest body = null;
            //var response = instance.CustomerFindSubscriberById2(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerGetGroupByCode
        /// </summary>
        [Fact]
        public void CustomerGetGroupByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGetGroupByCodeRequest body = null;
            //var response = instance.CustomerGetGroupByCode(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerGetGroupByCode2
        /// </summary>
        [Fact]
        public void CustomerGetGroupByCode2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGetGroupByCodeRequest body = null;
            //var response = instance.CustomerGetGroupByCode2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerGetGroupById
        /// </summary>
        [Fact]
        public void CustomerGetGroupByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGetGroupByIdRequest body = null;
            //var response = instance.CustomerGetGroupById(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerGetGroupById2
        /// </summary>
        [Fact]
        public void CustomerGetGroupById2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGetGroupByIdRequest body = null;
            //var response = instance.CustomerGetGroupById2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerGrantPermissions
        /// </summary>
        [Fact]
        public void CustomerGrantPermissionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGrantPermissionsRequest body = null;
            //var response = instance.CustomerGrantPermissions(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerGrantPermissions2
        /// </summary>
        [Fact]
        public void CustomerGrantPermissions2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerGrantPermissionsRequest body = null;
            //var response = instance.CustomerGrantPermissions2(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerListConsents
        /// </summary>
        [Fact]
        public void CustomerListConsentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerListConsentsRequest body = null;
            //var response = instance.CustomerListConsents(body);
            //Assert.IsType<CustomerListConsentsResponse>(response);
        }

        /// <summary>
        /// Test CustomerListCustomers
        /// </summary>
        [Fact]
        public void CustomerListCustomersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerListCustomersRequest body = null;
            //var response = instance.CustomerListCustomers(body);
            //Assert.IsType<CustomerListCustomersResponse>(response);
        }

        /// <summary>
        /// Test CustomerListCustomers2
        /// </summary>
        [Fact]
        public void CustomerListCustomers2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerListCustomersRequest body = null;
            //var response = instance.CustomerListCustomers2(body);
            //Assert.IsType<CustomerListCustomersResponse>(response);
        }

        /// <summary>
        /// Test CustomerListGroups
        /// </summary>
        [Fact]
        public void CustomerListGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerListGroupsRequest body = null;
            //var response = instance.CustomerListGroups(body);
            //Assert.IsType<CustomerListGroupsResponse>(response);
        }

        /// <summary>
        /// Test CustomerListGroups2
        /// </summary>
        [Fact]
        public void CustomerListGroups2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerListGroupsRequest body = null;
            //var response = instance.CustomerListGroups2(body);
            //Assert.IsType<CustomerListGroupsResponse>(response);
        }

        /// <summary>
        /// Test CustomerRemoveCustomerFromGroup
        /// </summary>
        [Fact]
        public void CustomerRemoveCustomerFromGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRemoveCustomerFromGroupRequest body = null;
            //var response = instance.CustomerRemoveCustomerFromGroup(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerRemoveCustomerFromGroup2
        /// </summary>
        [Fact]
        public void CustomerRemoveCustomerFromGroup2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRemoveCustomerFromGroupRequest body = null;
            //var response = instance.CustomerRemoveCustomerFromGroup2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerRemoveDefaultAddress
        /// </summary>
        [Fact]
        public void CustomerRemoveDefaultAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRemoveDefaultAddressRequest body = null;
            //var response = instance.CustomerRemoveDefaultAddress(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerRemoveDefaultAddress2
        /// </summary>
        [Fact]
        public void CustomerRemoveDefaultAddress2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRemoveDefaultAddressRequest body = null;
            //var response = instance.CustomerRemoveDefaultAddress2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerRevokePermissions
        /// </summary>
        [Fact]
        public void CustomerRevokePermissionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRevokePermissionsRequest body = null;
            //var response = instance.CustomerRevokePermissions(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerRevokePermissions2
        /// </summary>
        [Fact]
        public void CustomerRevokePermissions2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerRevokePermissionsRequest body = null;
            //var response = instance.CustomerRevokePermissions2(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerSearch
        /// </summary>
        [Fact]
        public void CustomerSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSearchRequest body = null;
            //var response = instance.CustomerSearch(body);
            //Assert.IsType<CustomerSearchResponse>(response);
        }

        /// <summary>
        /// Test CustomerSearch2
        /// </summary>
        [Fact]
        public void CustomerSearch2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSearchRequest body = null;
            //var response = instance.CustomerSearch2(body);
            //Assert.IsType<CustomerSearchResponse>(response);
        }

        /// <summary>
        /// Test CustomerSetDefaultAddress
        /// </summary>
        [Fact]
        public void CustomerSetDefaultAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSetDefaultAddressRequest body = null;
            //var response = instance.CustomerSetDefaultAddress(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerSetDefaultAddress2
        /// </summary>
        [Fact]
        public void CustomerSetDefaultAddress2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSetDefaultAddressRequest body = null;
            //var response = instance.CustomerSetDefaultAddress2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerSetPermissions
        /// </summary>
        [Fact]
        public void CustomerSetPermissionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSetPermissionsRequest body = null;
            //var response = instance.CustomerSetPermissions(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerSetPermissions2
        /// </summary>
        [Fact]
        public void CustomerSetPermissions2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerSetPermissionsRequest body = null;
            //var response = instance.CustomerSetPermissions2(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerUnassignAgent
        /// </summary>
        [Fact]
        public void CustomerUnassignAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUnassignAgentRequest body = null;
            //var response = instance.CustomerUnassignAgent(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test CustomerUnsubscribe
        /// </summary>
        [Fact]
        public void CustomerUnsubscribeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUnsubscribeRequest body = null;
            //var response = instance.CustomerUnsubscribe(body);
            //Assert.IsType<CustomerUnsubscribeResponse>(response);
        }

        /// <summary>
        /// Test CustomerUnsubscribe2
        /// </summary>
        [Fact]
        public void CustomerUnsubscribe2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUnsubscribeRequest body = null;
            //var response = instance.CustomerUnsubscribe2(body);
            //Assert.IsType<CustomerUnsubscribeResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdate
        /// </summary>
        [Fact]
        public void CustomerUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateRequest body = null;
            //var response = instance.CustomerUpdate(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdate2
        /// </summary>
        [Fact]
        public void CustomerUpdate2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateRequest body = null;
            //var response = instance.CustomerUpdate2(body);
            //Assert.IsType<CustomerCustomerResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateAddress
        /// </summary>
        [Fact]
        public void CustomerUpdateAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressUpdateRequest body = null;
            //var response = instance.CustomerUpdateAddress(body);
            //Assert.IsType<CustomerAddressUpdateResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateAddress2
        /// </summary>
        [Fact]
        public void CustomerUpdateAddress2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerAddressUpdateRequest body = null;
            //var response = instance.CustomerUpdateAddress2(body);
            //Assert.IsType<CustomerAddressUpdateResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateGroup
        /// </summary>
        [Fact]
        public void CustomerUpdateGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateGroupRequest body = null;
            //var response = instance.CustomerUpdateGroup(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateGroup2
        /// </summary>
        [Fact]
        public void CustomerUpdateGroup2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateGroupRequest body = null;
            //var response = instance.CustomerUpdateGroup2(body);
            //Assert.IsType<CustomerGroupResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateSubscriber
        /// </summary>
        [Fact]
        public void CustomerUpdateSubscriberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateSubscriberRequest body = null;
            //var response = instance.CustomerUpdateSubscriber(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }

        /// <summary>
        /// Test CustomerUpdateSubscriber2
        /// </summary>
        [Fact]
        public void CustomerUpdateSubscriber2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerUpdateSubscriberRequest body = null;
            //var response = instance.CustomerUpdateSubscriber2(body);
            //Assert.IsType<CustomerSubscriberResponse>(response);
        }
    }
}
