/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// Defines BulkUpdateRequestAction
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BulkUpdateRequestAction
    {
        /// <summary>
        /// Enum ENABLE for value: ENABLE
        /// </summary>
        [EnumMember(Value = "ENABLE")]
        ENABLE = 1,

        /// <summary>
        /// Enum DISABLE for value: DISABLE
        /// </summary>
        [EnumMember(Value = "DISABLE")]
        DISABLE = 2,

        /// <summary>
        /// Enum DELETE for value: DELETE
        /// </summary>
        [EnumMember(Value = "DELETE")]
        DELETE = 3
    }

}
