/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// CustomerNewsletterRequest
    /// </summary>
    [DataContract(Name = "customerNewsletterRequest")]
    public partial class CustomerNewsletterRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerNewsletterRequest" /> class.
        /// </summary>
        /// <param name="newsletterGrn">newsletterGrn.</param>
        /// <param name="name">name.</param>
        /// <param name="subscribed">subscribed.</param>
        public CustomerNewsletterRequest(string newsletterGrn = default(string), string name = default(string), bool subscribed = default(bool))
        {
            this.NewsletterGrn = newsletterGrn;
            this.Name = name;
            this.Subscribed = subscribed;
        }

        /// <summary>
        /// Gets or Sets NewsletterGrn
        /// </summary>
        [DataMember(Name = "newsletterGrn", EmitDefaultValue = false)]
        public string NewsletterGrn { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Subscribed
        /// </summary>
        [DataMember(Name = "subscribed", EmitDefaultValue = true)]
        public bool Subscribed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerNewsletterRequest {\n");
            sb.Append("  NewsletterGrn: ").Append(NewsletterGrn).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Subscribed: ").Append(Subscribed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
