/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// CustomerFindManyRequestFilter
    /// </summary>
    [DataContract(Name = "customerFindManyRequestFilter")]
    public partial class CustomerFindManyRequestFilter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerFindManyRequestFilter" /> class.
        /// </summary>
        /// <param name="newsletter">newsletter.</param>
        /// <param name="agentGrn">agentGrn.</param>
        public CustomerFindManyRequestFilter(bool newsletter = default(bool), string agentGrn = default(string))
        {
            this.Newsletter = newsletter;
            this.AgentGrn = agentGrn;
        }

        /// <summary>
        /// Gets or Sets Newsletter
        /// </summary>
        [DataMember(Name = "newsletter", EmitDefaultValue = true)]
        public bool Newsletter { get; set; }

        /// <summary>
        /// Gets or Sets AgentGrn
        /// </summary>
        [DataMember(Name = "agentGrn", EmitDefaultValue = false)]
        public string AgentGrn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerFindManyRequestFilter {\n");
            sb.Append("  Newsletter: ").Append(Newsletter).Append("\n");
            sb.Append("  AgentGrn: ").Append(AgentGrn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
