/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// Defines customerConsentSource
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CustomerConsentSource
    {
        /// <summary>
        /// Enum UNKNOWN for value: CONSENT_SOURCE_UNKNOWN
        /// </summary>
        [EnumMember(Value = "CONSENT_SOURCE_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum FRONTEND for value: CONSENT_SOURCE_FRONTEND
        /// </summary>
        [EnumMember(Value = "CONSENT_SOURCE_FRONTEND")]
        FRONTEND = 2,

        /// <summary>
        /// Enum BACKOFFICE for value: CONSENT_SOURCE_BACKOFFICE
        /// </summary>
        [EnumMember(Value = "CONSENT_SOURCE_BACKOFFICE")]
        BACKOFFICE = 3,

        /// <summary>
        /// Enum BACKEND for value: CONSENT_SOURCE_BACKEND
        /// </summary>
        [EnumMember(Value = "CONSENT_SOURCE_BACKEND")]
        BACKEND = 4
    }

}
