/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// CustomerUnsubscribeResponse
    /// </summary>
    [DataContract(Name = "customerUnsubscribeResponse")]
    public partial class CustomerUnsubscribeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerUnsubscribeResponse" /> class.
        /// </summary>
        /// <param name="response">response.</param>
        /// <param name="subscriberExist">subscriberExist.</param>
        /// <param name="activeNewsletterGrn">activeNewsletterGrn.</param>
        public CustomerUnsubscribeResponse(bool response = default(bool), bool subscriberExist = default(bool), List<string> activeNewsletterGrn = default(List<string>))
        {
            this.Response = response;
            this.SubscriberExist = subscriberExist;
            this.ActiveNewsletterGrn = activeNewsletterGrn;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Response
        /// </summary>
        [DataMember(Name = "response", EmitDefaultValue = true)]
        public bool Response { get; set; }

        /// <summary>
        /// Gets or Sets SubscriberExist
        /// </summary>
        [DataMember(Name = "subscriberExist", EmitDefaultValue = true)]
        public bool SubscriberExist { get; set; }

        /// <summary>
        /// Gets or Sets ActiveNewsletterGrn
        /// </summary>
        [DataMember(Name = "activeNewsletterGrn", EmitDefaultValue = false)]
        public List<string> ActiveNewsletterGrn { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerUnsubscribeResponse {\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("  SubscriberExist: ").Append(SubscriberExist).Append("\n");
            sb.Append("  ActiveNewsletterGrn: ").Append(ActiveNewsletterGrn).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
