/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// Defines customerPermission
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CustomerPermission
    {
        /// <summary>
        /// Enum UNKNOWN for value: PERMISSION_UNKNOWN
        /// </summary>
        [EnumMember(Value = "PERMISSION_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum LOGIN for value: PERMISSION_LOGIN
        /// </summary>
        [EnumMember(Value = "PERMISSION_LOGIN")]
        LOGIN = 2,

        /// <summary>
        /// Enum BUY for value: PERMISSION_BUY
        /// </summary>
        [EnumMember(Value = "PERMISSION_BUY")]
        BUY = 3
    }

}
