/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = customer.Client.OpenAPIDateConverter;

namespace customer.Model
{
    /// <summary>
    /// Defines PasswordPasswordType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PasswordPasswordType
    {
        /// <summary>
        /// Enum UNKNOWN for value: PASSWORD_TYPE_UNKNOWN
        /// </summary>
        [EnumMember(Value = "PASSWORD_TYPE_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum MAGENTO1 for value: PASSWORD_TYPE_MAGENTO1
        /// </summary>
        [EnumMember(Value = "PASSWORD_TYPE_MAGENTO1")]
        MAGENTO1 = 2,

        /// <summary>
        /// Enum SYLIUS for value: PASSWORD_TYPE_SYLIUS
        /// </summary>
        [EnumMember(Value = "PASSWORD_TYPE_SYLIUS")]
        SYLIUS = 3,

        /// <summary>
        /// Enum MAGENTO2 for value: PASSWORD_TYPE_MAGENTO2
        /// </summary>
        [EnumMember(Value = "PASSWORD_TYPE_MAGENTO2")]
        MAGENTO2 = 4
    }

}
