/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerFindManyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerFindManyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerFindManyResponse
        //private CustomerFindManyResponse instance;

        public CustomerFindManyResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerFindManyResponse
            //instance = new CustomerFindManyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerFindManyResponse
        /// </summary>
        [Fact]
        public void CustomerFindManyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerFindManyResponse
            //Assert.IsType<CustomerFindManyResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Customers'
        /// </summary>
        [Fact]
        public void CustomersTest()
        {
            // TODO unit test for the property 'Customers'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
