/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUnsubscribeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUnsubscribeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUnsubscribeRequest
        //private CustomerUnsubscribeRequest instance;

        public CustomerUnsubscribeRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerUnsubscribeRequest
            //instance = new CustomerUnsubscribeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUnsubscribeRequest
        /// </summary>
        [Fact]
        public void CustomerUnsubscribeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUnsubscribeRequest
            //Assert.IsType<CustomerUnsubscribeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'NewsletterGrn'
        /// </summary>
        [Fact]
        public void NewsletterGrnTest()
        {
            // TODO unit test for the property 'NewsletterGrn'
        }
    }
}
