/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAddCustomerToGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAddCustomerToGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAddCustomerToGroupRequest
        //private CustomerAddCustomerToGroupRequest instance;

        public CustomerAddCustomerToGroupRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerAddCustomerToGroupRequest
            //instance = new CustomerAddCustomerToGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAddCustomerToGroupRequest
        /// </summary>
        [Fact]
        public void CustomerAddCustomerToGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAddCustomerToGroupRequest
            //Assert.IsType<CustomerAddCustomerToGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
    }
}
