/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUpdateGroupRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUpdateGroupRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUpdateGroupRequestPayload
        //private CustomerUpdateGroupRequestPayload instance;

        public CustomerUpdateGroupRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of CustomerUpdateGroupRequestPayload
            //instance = new CustomerUpdateGroupRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUpdateGroupRequestPayload
        /// </summary>
        [Fact]
        public void CustomerUpdateGroupRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUpdateGroupRequestPayload
            //Assert.IsType<CustomerUpdateGroupRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
