/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerEMFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerEMFieldsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerEMFields
        //private CustomerEMFields instance;

        public CustomerEMFieldsTests()
        {
            // TODO uncomment below to create an instance of CustomerEMFields
            //instance = new CustomerEMFields();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerEMFields
        /// </summary>
        [Fact]
        public void CustomerEMFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerEMFields
            //Assert.IsType<CustomerEMFields>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Fact]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }

        /// <summary>
        /// Test the property 'EntityCode'
        /// </summary>
        [Fact]
        public void EntityCodeTest()
        {
            // TODO unit test for the property 'EntityCode'
        }
    }
}
