/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerListCustomersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerListCustomersResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerListCustomersResponse
        //private CustomerListCustomersResponse instance;

        public CustomerListCustomersResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerListCustomersResponse
            //instance = new CustomerListCustomersResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerListCustomersResponse
        /// </summary>
        [Fact]
        public void CustomerListCustomersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerListCustomersResponse
            //Assert.IsType<CustomerListCustomersResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Customers'
        /// </summary>
        [Fact]
        public void CustomersTest()
        {
            // TODO unit test for the property 'Customers'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
