/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUpdateRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUpdateRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUpdateRequestPayload
        //private CustomerUpdateRequestPayload instance;

        public CustomerUpdateRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of CustomerUpdateRequestPayload
            //instance = new CustomerUpdateRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUpdateRequestPayload
        /// </summary>
        [Fact]
        public void CustomerUpdateRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUpdateRequestPayload
            //Assert.IsType<CustomerUpdateRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Em'
        /// </summary>
        [Fact]
        public void EmTest()
        {
            // TODO unit test for the property 'Em'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Fact]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }

        /// <summary>
        /// Test the property 'DefaultBillingAddressId'
        /// </summary>
        [Fact]
        public void DefaultBillingAddressIdTest()
        {
            // TODO unit test for the property 'DefaultBillingAddressId'
        }

        /// <summary>
        /// Test the property 'DefaultShippingAddressId'
        /// </summary>
        [Fact]
        public void DefaultShippingAddressIdTest()
        {
            // TODO unit test for the property 'DefaultShippingAddressId'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Fact]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'Newsletters'
        /// </summary>
        [Fact]
        public void NewslettersTest()
        {
            // TODO unit test for the property 'Newsletters'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'MigratedPassword'
        /// </summary>
        [Fact]
        public void MigratedPasswordTest()
        {
            // TODO unit test for the property 'MigratedPassword'
        }

        /// <summary>
        /// Test the property 'PreferredLocale'
        /// </summary>
        [Fact]
        public void PreferredLocaleTest()
        {
            // TODO unit test for the property 'PreferredLocale'
        }

        /// <summary>
        /// Test the property 'TaxCode'
        /// </summary>
        [Fact]
        public void TaxCodeTest()
        {
            // TODO unit test for the property 'TaxCode'
        }

        /// <summary>
        /// Test the property 'CertifiedEmail'
        /// </summary>
        [Fact]
        public void CertifiedEmailTest()
        {
            // TODO unit test for the property 'CertifiedEmail'
        }

        /// <summary>
        /// Test the property 'SdiCode'
        /// </summary>
        [Fact]
        public void SdiCodeTest()
        {
            // TODO unit test for the property 'SdiCode'
        }

        /// <summary>
        /// Test the property 'FiscalCode'
        /// </summary>
        [Fact]
        public void FiscalCodeTest()
        {
            // TODO unit test for the property 'FiscalCode'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'ExternalIds'
        /// </summary>
        [Fact]
        public void ExternalIdsTest()
        {
            // TODO unit test for the property 'ExternalIds'
        }

        /// <summary>
        /// Test the property 'Consent'
        /// </summary>
        [Fact]
        public void ConsentTest()
        {
            // TODO unit test for the property 'Consent'
        }
    }
}
