/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUpdateSubscriberRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUpdateSubscriberRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUpdateSubscriberRequest
        //private CustomerUpdateSubscriberRequest instance;

        public CustomerUpdateSubscriberRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerUpdateSubscriberRequest
            //instance = new CustomerUpdateSubscriberRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUpdateSubscriberRequest
        /// </summary>
        [Fact]
        public void CustomerUpdateSubscriberRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUpdateSubscriberRequest
            //Assert.IsType<CustomerUpdateSubscriberRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Subscriber'
        /// </summary>
        [Fact]
        public void SubscriberTest()
        {
            // TODO unit test for the property 'Subscriber'
        }

        /// <summary>
        /// Test the property 'FieldMask'
        /// </summary>
        [Fact]
        public void FieldMaskTest()
        {
            // TODO unit test for the property 'FieldMask'
        }
    }
}
