/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerFindByEmailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerFindByEmailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerFindByEmailRequest
        //private CustomerFindByEmailRequest instance;

        public CustomerFindByEmailRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerFindByEmailRequest
            //instance = new CustomerFindByEmailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerFindByEmailRequest
        /// </summary>
        [Fact]
        public void CustomerFindByEmailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerFindByEmailRequest
            //Assert.IsType<CustomerFindByEmailRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
