/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerFindSubscriberByEmailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerFindSubscriberByEmailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerFindSubscriberByEmailRequest
        //private CustomerFindSubscriberByEmailRequest instance;

        public CustomerFindSubscriberByEmailRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerFindSubscriberByEmailRequest
            //instance = new CustomerFindSubscriberByEmailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerFindSubscriberByEmailRequest
        /// </summary>
        [Fact]
        public void CustomerFindSubscriberByEmailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerFindSubscriberByEmailRequest
            //Assert.IsType<CustomerFindSubscriberByEmailRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SubscriberEmail'
        /// </summary>
        [Fact]
        public void SubscriberEmailTest()
        {
            // TODO unit test for the property 'SubscriberEmail'
        }
    }
}
