/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAddressDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAddressDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAddressDeleteResponse
        //private CustomerAddressDeleteResponse instance;

        public CustomerAddressDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerAddressDeleteResponse
            //instance = new CustomerAddressDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAddressDeleteResponse
        /// </summary>
        [Fact]
        public void CustomerAddressDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAddressDeleteResponse
            //Assert.IsType<CustomerAddressDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
    }
}
