/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerListCustomersRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerListCustomersRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerListCustomersRequestFilter
        //private CustomerListCustomersRequestFilter instance;

        public CustomerListCustomersRequestFilterTests()
        {
            // TODO uncomment below to create an instance of CustomerListCustomersRequestFilter
            //instance = new CustomerListCustomersRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerListCustomersRequestFilter
        /// </summary>
        [Fact]
        public void CustomerListCustomersRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerListCustomersRequestFilter
            //Assert.IsType<CustomerListCustomersRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Genders'
        /// </summary>
        [Fact]
        public void GendersTest()
        {
            // TODO unit test for the property 'Genders'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Fact]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }

        /// <summary>
        /// Test the property 'AgentGrn'
        /// </summary>
        [Fact]
        public void AgentGrnTest()
        {
            // TODO unit test for the property 'AgentGrn'
        }
    }
}
