/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAddressCustomerResponseKind
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAddressCustomerResponseKindTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAddressCustomerResponseKind
        //private CustomerAddressCustomerResponseKind instance;

        public CustomerAddressCustomerResponseKindTests()
        {
            // TODO uncomment below to create an instance of CustomerAddressCustomerResponseKind
            //instance = new CustomerAddressCustomerResponseKind();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAddressCustomerResponseKind
        /// </summary>
        [Fact]
        public void CustomerAddressCustomerResponseKindInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAddressCustomerResponseKind
            //Assert.IsType<CustomerAddressCustomerResponseKind>(instance);
        }
    }
}
