/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerGetGroupByCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerGetGroupByCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerGetGroupByCodeRequest
        //private CustomerGetGroupByCodeRequest instance;

        public CustomerGetGroupByCodeRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerGetGroupByCodeRequest
            //instance = new CustomerGetGroupByCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerGetGroupByCodeRequest
        /// </summary>
        [Fact]
        public void CustomerGetGroupByCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerGetGroupByCodeRequest
            //Assert.IsType<CustomerGetGroupByCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
