/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerRevokePermissionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerRevokePermissionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerRevokePermissionsRequest
        //private CustomerRevokePermissionsRequest instance;

        public CustomerRevokePermissionsRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerRevokePermissionsRequest
            //instance = new CustomerRevokePermissionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerRevokePermissionsRequest
        /// </summary>
        [Fact]
        public void CustomerRevokePermissionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerRevokePermissionsRequest
            //Assert.IsType<CustomerRevokePermissionsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }
    }
}
