/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerRemoveDefaultAddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerRemoveDefaultAddressRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerRemoveDefaultAddressRequest
        //private CustomerRemoveDefaultAddressRequest instance;

        public CustomerRemoveDefaultAddressRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerRemoveDefaultAddressRequest
            //instance = new CustomerRemoveDefaultAddressRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerRemoveDefaultAddressRequest
        /// </summary>
        [Fact]
        public void CustomerRemoveDefaultAddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerRemoveDefaultAddressRequest
            //Assert.IsType<CustomerRemoveDefaultAddressRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'AddressId'
        /// </summary>
        [Fact]
        public void AddressIdTest()
        {
            // TODO unit test for the property 'AddressId'
        }
    }
}
