/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerSubscriberResponseWithNewsletterRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerSubscriberResponseWithNewsletterRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerSubscriberResponseWithNewsletterRequest
        //private CustomerSubscriberResponseWithNewsletterRequest instance;

        public CustomerSubscriberResponseWithNewsletterRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerSubscriberResponseWithNewsletterRequest
            //instance = new CustomerSubscriberResponseWithNewsletterRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerSubscriberResponseWithNewsletterRequest
        /// </summary>
        [Fact]
        public void CustomerSubscriberResponseWithNewsletterRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerSubscriberResponseWithNewsletterRequest
            //Assert.IsType<CustomerSubscriberResponseWithNewsletterRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Fact]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }

        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Fact]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }

        /// <summary>
        /// Test the property 'Em'
        /// </summary>
        [Fact]
        public void EmTest()
        {
            // TODO unit test for the property 'Em'
        }

        /// <summary>
        /// Test the property 'PreferredLocale'
        /// </summary>
        [Fact]
        public void PreferredLocaleTest()
        {
            // TODO unit test for the property 'PreferredLocale'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Newsletters'
        /// </summary>
        [Fact]
        public void NewslettersTest()
        {
            // TODO unit test for the property 'Newsletters'
        }

        /// <summary>
        /// Test the property 'Consent'
        /// </summary>
        [Fact]
        public void ConsentTest()
        {
            // TODO unit test for the property 'Consent'
        }
    }
}
