/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAssignAgentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAssignAgentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAssignAgentRequest
        //private CustomerAssignAgentRequest instance;

        public CustomerAssignAgentRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerAssignAgentRequest
            //instance = new CustomerAssignAgentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAssignAgentRequest
        /// </summary>
        [Fact]
        public void CustomerAssignAgentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAssignAgentRequest
            //Assert.IsType<CustomerAssignAgentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'AgentGrn'
        /// </summary>
        [Fact]
        public void AgentGrnTest()
        {
            // TODO unit test for the property 'AgentGrn'
        }

        /// <summary>
        /// Test the property 'CustomerIds'
        /// </summary>
        [Fact]
        public void CustomerIdsTest()
        {
            // TODO unit test for the property 'CustomerIds'
        }
    }
}
