/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerListGroupsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerListGroupsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerListGroupsRequest
        //private CustomerListGroupsRequest instance;

        public CustomerListGroupsRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerListGroupsRequest
            //instance = new CustomerListGroupsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerListGroupsRequest
        /// </summary>
        [Fact]
        public void CustomerListGroupsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerListGroupsRequest
            //Assert.IsType<CustomerListGroupsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Fact]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'FiltersMask'
        /// </summary>
        [Fact]
        public void FiltersMaskTest()
        {
            // TODO unit test for the property 'FiltersMask'
        }
    }
}
