/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerListGroupsRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerListGroupsRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerListGroupsRequestFilter
        //private CustomerListGroupsRequestFilter instance;

        public CustomerListGroupsRequestFilterTests()
        {
            // TODO uncomment below to create an instance of CustomerListGroupsRequestFilter
            //instance = new CustomerListGroupsRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerListGroupsRequestFilter
        /// </summary>
        [Fact]
        public void CustomerListGroupsRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerListGroupsRequestFilter
            //Assert.IsType<CustomerListGroupsRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'SearchTerm'
        /// </summary>
        [Fact]
        public void SearchTermTest()
        {
            // TODO unit test for the property 'SearchTerm'
        }
    }
}
