/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUnsubscribeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUnsubscribeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUnsubscribeResponse
        //private CustomerUnsubscribeResponse instance;

        public CustomerUnsubscribeResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerUnsubscribeResponse
            //instance = new CustomerUnsubscribeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUnsubscribeResponse
        /// </summary>
        [Fact]
        public void CustomerUnsubscribeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUnsubscribeResponse
            //Assert.IsType<CustomerUnsubscribeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

        /// <summary>
        /// Test the property 'SubscriberExist'
        /// </summary>
        [Fact]
        public void SubscriberExistTest()
        {
            // TODO unit test for the property 'SubscriberExist'
        }

        /// <summary>
        /// Test the property 'ActiveNewsletterGrn'
        /// </summary>
        [Fact]
        public void ActiveNewsletterGrnTest()
        {
            // TODO unit test for the property 'ActiveNewsletterGrn'
        }
    }
}
