/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUpdateGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUpdateGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUpdateGroupRequest
        //private CustomerUpdateGroupRequest instance;

        public CustomerUpdateGroupRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerUpdateGroupRequest
            //instance = new CustomerUpdateGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUpdateGroupRequest
        /// </summary>
        [Fact]
        public void CustomerUpdateGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUpdateGroupRequest
            //Assert.IsType<CustomerUpdateGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'FieldMask'
        /// </summary>
        [Fact]
        public void FieldMaskTest()
        {
            // TODO unit test for the property 'FieldMask'
        }
    }
}
