/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerDeleteGroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerDeleteGroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerDeleteGroupResponse
        //private CustomerDeleteGroupResponse instance;

        public CustomerDeleteGroupResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerDeleteGroupResponse
            //instance = new CustomerDeleteGroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerDeleteGroupResponse
        /// </summary>
        [Fact]
        public void CustomerDeleteGroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerDeleteGroupResponse
            //Assert.IsType<CustomerDeleteGroupResponse>(instance);
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
    }
}
