/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerFindManyRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerFindManyRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerFindManyRequestFilter
        //private CustomerFindManyRequestFilter instance;

        public CustomerFindManyRequestFilterTests()
        {
            // TODO uncomment below to create an instance of CustomerFindManyRequestFilter
            //instance = new CustomerFindManyRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerFindManyRequestFilter
        /// </summary>
        [Fact]
        public void CustomerFindManyRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerFindManyRequestFilter
            //Assert.IsType<CustomerFindManyRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Newsletter'
        /// </summary>
        [Fact]
        public void NewsletterTest()
        {
            // TODO unit test for the property 'Newsletter'
        }

        /// <summary>
        /// Test the property 'AgentGrn'
        /// </summary>
        [Fact]
        public void AgentGrnTest()
        {
            // TODO unit test for the property 'AgentGrn'
        }
    }
}
