/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAddressUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAddressUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAddressUpdateRequest
        //private CustomerAddressUpdateRequest instance;

        public CustomerAddressUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerAddressUpdateRequest
            //instance = new CustomerAddressUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAddressUpdateRequest
        /// </summary>
        [Fact]
        public void CustomerAddressUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAddressUpdateRequest
            //Assert.IsType<CustomerAddressUpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'FieldMask'
        /// </summary>
        [Fact]
        public void FieldMaskTest()
        {
            // TODO unit test for the property 'FieldMask'
        }
    }
}
