/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerCreateConsentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerCreateConsentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerCreateConsentRequest
        //private CustomerCreateConsentRequest instance;

        public CustomerCreateConsentRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerCreateConsentRequest
            //instance = new CustomerCreateConsentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerCreateConsentRequest
        /// </summary>
        [Fact]
        public void CustomerCreateConsentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerCreateConsentRequest
            //Assert.IsType<CustomerCreateConsentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Fact]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
    }
}
