/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing ListConsentsRequestFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListConsentsRequestFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListConsentsRequestFilters
        //private ListConsentsRequestFilters instance;

        public ListConsentsRequestFiltersTests()
        {
            // TODO uncomment below to create an instance of ListConsentsRequestFilters
            //instance = new ListConsentsRequestFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListConsentsRequestFilters
        /// </summary>
        [Fact]
        public void ListConsentsRequestFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListConsentsRequestFilters
            //Assert.IsType<ListConsentsRequestFilters>(instance);
        }

        /// <summary>
        /// Test the property 'SubjectIds'
        /// </summary>
        [Fact]
        public void SubjectIdsTest()
        {
            // TODO unit test for the property 'SubjectIds'
        }
    }
}
