/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing ListCustomersRequestFilterDate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCustomersRequestFilterDateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCustomersRequestFilterDate
        //private ListCustomersRequestFilterDate instance;

        public ListCustomersRequestFilterDateTests()
        {
            // TODO uncomment below to create an instance of ListCustomersRequestFilterDate
            //instance = new ListCustomersRequestFilterDate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCustomersRequestFilterDate
        /// </summary>
        [Fact]
        public void ListCustomersRequestFilterDateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCustomersRequestFilterDate
            //Assert.IsType<ListCustomersRequestFilterDate>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
    }
}
