/*
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using customer.Model;
using customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace customer.Test.Model
{
    /// <summary>
    ///  Class for testing ListConsentsRequestSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListConsentsRequestSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListConsentsRequestSort
        //private ListConsentsRequestSort instance;

        public ListConsentsRequestSortTests()
        {
            // TODO uncomment below to create an instance of ListConsentsRequestSort
            //instance = new ListConsentsRequestSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListConsentsRequestSort
        /// </summary>
        [Fact]
        public void ListConsentsRequestSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListConsentsRequestSort
            //Assert.IsType<ListConsentsRequestSort>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
